version: "3"

services:
        web:
                build: .
                container_name: js-fastapi-monitoring
                volumes:
                        - .:/code
                ports:
                        - "5000:80"
                environment:
                        - ENABLE_METRICS=true
